name: Build EDMC for Windows

on:
  push:
    tags:
      - "Release/*"
  workflow_dispatch:

jobs:
  checkout_all:
    name: Checkout EDMC and submodules
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

  python_setup_base:
    name: Install python base
    runs-on: windows-2019
    needs: checkout_all

    steps:
      - uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.10.2"
          architecture: "x86"

  python_requirements:
    name: Install application python requirements
    runs-on: windows-2019
    needs: setup_python_base

    steps:
      - name: Install python tools
        run: |
          pip install wheel
          pip install -r requirements-dev.txt

  winsparkle_install:
    name: Download and unpack WinSparkle files
    runs-on: windows-2019
    needs: perform_checkouts

    defaults:
      run:
        shell: powershell

    steps:
      - name: Download winsparkle
        run: |
          Invoke-Webrequest -UseBasicParsing https://github.com/vslavik/winsparkle/releases/download/v0.7.0/WinSparkle-0.7.0.zip -OutFile out.zip
          Expand-Archive out.zip
          Move-Item 'out\WinSparkle-0.7.0\Release\*' '.\'

  edmc_setup_py2exe:
    name: Invoke setup.py py2exe
    runs-on: windows-2019
    needs: [ perform_checkouts, setup_python_base, python_requirements, winsparkle_install ]

    steps:
      - name: Build EDMC
        run: |
          python setup.py py2exe

  edmc_upload_build:
    name: Upload resulting build files
    runs-on: windows-2019
    needs: edmc_setup_py2exe

    steps:
      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: Built files
          path: EDMarketConnector_win*.msi

  edmc_release:
    name: Release new version
    runs-on: ubuntu-latest
    needs: edmc_upload_build
    if: "${{ github.event_name != 'workflow_dispatch' }}"

    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: Built files
          path: ./
          
      - name: Hash files
        run: sha256sum EDMarketConnector_win*.msi > ./hashes.sum

      - name: Create Draft Release
        uses: "softprops/action-gh-release@v1"
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          draft: true
          prerelease: true
          discussion_category_name: "Announcement"
          files: |
            ./EDMarketConnector_win*.msi
            ./hashes.sum
